contact/urls.py
from django.urls import path
from contact import views, contact_forms

app_name = 'contact'

urlpatterns = [
    path('search/', views.search, name='search'),
    path('', views.index, name='index'),

    # contact CRUD
    path('contact/<int:contact_id>/detail/', views.contact, name='contact'),
    path('contact/create/', contact_forms.create, name='create'),
    #path('contact/<int:contact_id>/update/', views.contact, name='contact'),
    #path('contact/<int:contact_id>/delete/', views.contact, name='contact'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name

class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50)
    email = models.EmailField(max_length=254, blank=True)
    create_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m')
    category = models.ForeignKey(
        Category, 
        on_delete=models.SET_NULL,
        blank=True, null = True
        )
    owner = models.ForeignKey(
        User, 
        on_delete=models.SET_NULL,
        blank=True, null = True
    )


    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

contact/forms.py
from contact.models import Contact
from django import forms

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('first_name','last_name','phone',)

contact/views.py
from django.shortcuts import render, get_object_or_404, redirect
from contact.models import Contact
from django.http import Http404
from django.db.models import Q
from django.core.paginator import Paginator


def index(request):
    contacts = Contact.objects.all().filter(show=True)
    #.order_by('-id')

    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj': page_obj,
        'site_title': 'Contatos - '
    }

    return render(
        request, 
        'contact/index.html',
        context
    )

def search(request):
    search_value = request.GET.get('q','').strip()

    if search_value == '':
        return redirect('contact:index')# isso faz com que quando o usuário apaga o campo da pesquisa na url, o sistema redireciona para o index.html

    contacts = Contact.objects.all().filter(show=True).filter(Q(first_name__icontains=search_value) |
                                                              Q(last_name__icontains=search_value) |
                                                              Q(phone__icontains=search_value) |
                                                                Q(email__icontains=search_value))
    #.order_by('-id')

    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj':page_obj,
        'site_title': 'Search - ',
        'search_value': search_value,
    }

    return render(
        request, 
        'contact/index.html',
        context
    )


def contact(request, contact_id):
    #single_contact = Contact.objects.filter(pk=contact_id).first()
    #if single_contact is None:
    #    raise Http404()

    single_contact = get_object_or_404(
         #Contact.objects.filter(pk=contact_id, show=True)
         Contact, pk=contact_id, show=True
         )
    
    contact_name = f'{single_contact.first_name} {single_contact.last_name} -'
    context = {
        'contact': single_contact,
        'site_title': contact_name
        
    }

    return render(
        request, 
        'contact/contact.html',
        context
    )

contact/templates/contact/contact.html
{% extends 'global/base.html' %}

{% block content %}
<div class="single-contact">
    <h1 class="single-contact-name">
        {{ contact.first_name }} {{ contact.last_name }}
    </h1>

    <p><b>ID: </b>{{ contact.id }}</p>
    <p><b>E-mail: </b>{{ contact.email }}</p>
    <p><b>Phone: </b>{{ contact.phone }}</p>
    <p><b>Created Date: </b>{{ contact.create_date }}</p>
    <p><b>Description: </b>{{ contact.description }}</p>
    <p><b>Category: </b>{{ contact.category }}</p>
</div>
{% endblock %}

contact/templates/contact/create.html
{% extends 'global/base.html' %}

{% block content %}
<div class="form-wrapper">
    <h2>Contact</h2>

    <form action="{% url 'contact:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <!--os dados do formulario que estamos postando dentro da view são de fato do formulario-->
        <div class="form-content">
            {% for field in form %}
            <div class="form-group">
                <label for="id_first_name">LABEL</label>
                <input type="text" name="first_name" maxlength="255" id="id_first_name">
            </div>

            {% endfor %}
        </div>
    </form>
</div>
{% endblock content%}

contact/templates/contact/index.html
{% extends 'global/base.html' %}

{% block content %}

{% if page_obj %}

<div class="responsive-table">
    <table class="contacts-table">
        <caption class="table-caption">
            Contacts
        </caption>
        <thread>
            <tr class="table-row table-row-header">
                <th class="table-header">ID</th>
                <th class="table-header">First Name</th>
                <th class="table-header">Last Name</th>
                <th class="table-header">Phone</th>
                <th class="table-header">E-mail</th>
            </tr>
        </thread>
        <tbody>
            {% for contact in page_obj %}
            <tr class="table-row">
                <td class="table-cel">
                    <a href="{% url 'contact:contact' contact.id%}" class="table-link">
                        {{ contact.id }}
                    </a>
                </td>
                <td class="table-cel">
                    {{ contact.first_name }}
                </td>
                <td class="table-cel">
                    {{ contact.last_name }}
                </td>
                <td class="table-cel">
                    {{ contact.phone }}
                </td>
                <td class="table-cel">
                    {{ contact.email }}
                </td>
            </tr>

            {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<div class="single-contact">
    <h1 class="single-contact-name">
        Nenhum contato encontrado
    </h1>


</div>
{% endif %}
{% endblock content%}